// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTools.Context;

namespace WebTools.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebTools.Models.ReportList", b =>
                {
                    b.Property<string>("IdBieuMau")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CachIn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileLink")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IDPhienBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhoaPhong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaBM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayBanHanh")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhanMem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhanMem1")
                        .HasColumnType("int");

                    b.Property<string>("PhienBan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PhienBan1")
                        .HasColumnType("int");

                    b.Property<string>("QuyTrinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("STT")
                        .HasColumnType("int");

                    b.Property<string>("TenBM")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TheLoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiPM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URD")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTriIn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdBieuMau");

                    b.ToTable("ReportLists");
                });
#pragma warning restore 612, 618
        }
    }
}
